Playback controls
mapbox/assembly pull request #702
Opened 2017-02-01 00:30 UTC by sarahkleins

Adds a playback control example to /progress-bars/ examples.

<img width="771" alt="screenshot 2017-01-31 19 29 25" src="https://cloud.githubusercontent.com/assets/7318064/22490503/9ee67a1c-e7eb-11e6-9597-8cd93c5b9bab.png">

(Similar to below playback controls like:
![image](https://cloud.githubusercontent.com/assets/7318064/22490386/09ff30b0-e7eb-11e6-9ccd-2d75a4299685.png)
Example requested by @tristen 🙌 )

2017-02-15 18:42 UTC, davidtheclark reviewed
Very cool @sarahkleins! I left a couple of suggestions.

@tristen Do you want to review this? Should we merge it in before our next release?

2017-02-15 18:42 UTC, davidtheclark commented on site/examples/progress_bars.js
> +      <span class='block triangle--r triangle color-green color-green'></span>
Instead of using a `span` with the `block` class, how about using a `<div>`?

2017-02-15 18:42 UTC, davidtheclark commented on site/examples/progress_bars.js
> +        <div class='absolute top right bottom left m3 mh6 bg-green-light round-full' style='width:50%;'>
Is `mh6` a typo?

2017-02-15 19:08 UTC, sarahkleins commented
Thanks @davidtheclark! made these updates.

2017-02-15 20:06 UTC, tristen requested changes

2017-02-15 20:06 UTC, tristen commented on site/examples/progress_bars.js
> +    <div class='flex-child py18 pr12 pl18 border-r border--gray-light bg-white cursor-pointer'>
This element should have `round-l` applied to it.

2017-02-15 20:06 UTC, tristen commented on site/examples/progress_bars.js
> +      <div class='triangle--r triangle color-green color-green'></div>
This is a button. I would replace Line 9 with `<button>` element and include a hover state.

2017-02-15 20:06 UTC, tristen commented on site/examples/progress_bars.js
> +          <span class='absolute top right w30 h6 bg-green round-full'></span>
I think there's going to be an expectation that this is a playback scrubber. I think this should use a range input instead?

2017-02-15 20:41 UTC, sarahkleins commented on site/examples/progress_bars.js
> +          <span class='absolute top right w30 h6 bg-green round-full'></span>
thanks @tristen. Is this what you meant with a range input?
<img width="1087" alt="screenshot 2017-02-15 15 40 37" src="https://cloud.githubusercontent.com/assets/7318064/22994491/203c701c-f395-11e6-980e-d9b2535f7e0b.png">

2017-05-12 18:32 UTC, tristen approved these changes

2017-05-12 18:33 UTC, merged