Respond to switch hover state from its container
mapbox/assembly pull request #845
Opened 2017-08-18 18:03 UTC by tristen

- Fixes #844

2017-08-20 00:13 UTC, samanpwbb requested changes

2017-08-20 00:13 UTC, samanpwbb commented on src/forms.css
> -.switch:hover {
You'll need to update the switch rules in build-color-variants if you want this to work properly.

2017-08-20 13:40 UTC, tristen commented on src/forms.css
> -.switch:hover {
Hah, that's right 🤦‍♂️. Should be addressed now.

2017-08-21 19:03 UTC, samanpwbb approved these changes
🚜

2017-08-21 19:26 UTC, merged