Rework range input
mapbox/assembly pull request #999
Opened 2021-04-15 19:47 UTC by adrianababakanian

This PR closes https://github.com/mapbox/assembly/issues/980 and https://github.com/mapbox/assembly/issues/889

- Updates cursor to a pointer when inside the range input's clickable area. This makes it clearer that the user does not need to click _exactly_ on the pixels of the range track to update the position of the range thumb.
- Update range thumb's border-radius from 2px to 1px for consistency with style guide.
- Apply focus state to range thumb instead of track (_note: this point is still in progress_)

2021-04-16 18:44 UTC, adrianababakanian commented
👋 @samanpwbb I'm still trying to get 

> Apply focus state to range thumb instead of track

working, but just wanted to let you know that the other points are reviewable currently.

2021-04-16 22:43 UTC, adrianababakanian commented
@samanpwbb this PR is fully ready for review now!

2021-04-20 15:02 UTC, samanpwbb requested changes
This looks like a good start @adrianababakanian! Noticing two issues:

1. Make sure our focus style rule includes an assembly classname in it so we don't accidentally style non-Assembly ranges.
2. The active click area seems to be nice and large in Firefox, but not in Chrome. Can we investigate ways to increase the active area in Chrome?

2021-04-20 15:02 UTC, samanpwbb commented on src/focus.css
> +[data-assembly-focus-control='visible'] input[type=range]:focus::-moz-range-thumb {
This style rule needs a classname in it. As a principle, Assembly should leave things unstyled, unless they use Assembly classes. Imagine a case where an Assembly user wanted the behavior of the range input type, but needed to give it a custom style.

2021-04-20 15:02 UTC, samanpwbb commented on src/forms.css
> +  cursor: pointer;
👍 - this does make me wonder if the handle should have a _grabber_ cursor that transitions into grabbing on active?

2021-04-20 19:30 UTC, adrianababakanian commented on src/focus.css
> +[data-assembly-focus-control='visible'] input[type=range]:focus::-moz-range-thumb {
Ah, makes perfect sense!

2021-04-21 00:13 UTC, adrianababakanian commented
Thanks @samanpwbb , made some updates based on your feedback:

> Make sure our focus style rule includes an assembly classname in it so we don't accidentally style non-Assembly ranges.

Fixed by adding the `.range` classname back to the relevant selector 👍 

> The active click area seems to be nice and large in Firefox, but not in Chrome.

Thanks for catching this! I spent some time trying to research any well-documented solutions for handling this difference between Firefox and webkit-based browsers, but wasn't able to find anything specific. I ended up adding vertical padding to the range input element and then explicitly removing this padding for Firefox (since the clickable area already works as expected there). 

I'd appreciate feedback on this approach -- it feels a bit roundabout. 

> this does make me wonder if the handle should have a grabber cursor that transitions into grabbing on active?

I tried this out -- let me know what you think!

2021-04-21 00:16 UTC, adrianababakanian commented on test/__snapshots__/build-css.jest.js.snap
> +  cursor:grabbing;
For some reason, the cursor was not being updated when I used a comma-separated list of selectors -- I'm not sure why this is the case.

2021-04-21 01:40 UTC, samanpwbb approved these changes
Looks great🏅

2021-04-21 03:17 UTC, merged